package com.model.pojo;
// Generated May 23, 2016 12:30:14 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.ManyToMany;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user"
)
public class User implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;
    @Column(name = "RecordNo", length = 20)
    private String recordNo;
    @Column(name = "Name", length = 50)
    private String name;
    @Column(name = "Age")
    private Integer age;
    @Column(name = "Sex", length = 20)
    private String sex;
    @Temporal(TemporalType.DATE)
    @Column(name = "Dob", length = 10)
    private Date dob;
    @Column(name = "Remark", length = 50)
    private String remark;

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "role_user", joinColumns = @JoinColumn(name = "user_id"), inverseJoinColumns = @JoinColumn(name = "role_id"))
    private Set<Role> role;

    public User() {
    }

    public Set<Role> getRole() {
        return role;
    }

    public void setRole(Set<Role> role) {
        this.role = role;
    }
    
    
    
    public User(String recordNo, String name, Integer age, String sex, Date dob, String remark) {
        this.recordNo = recordNo;
        this.name = name;
        this.age = age;
        this.sex = sex;
        this.dob = dob;
        this.remark = remark;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getRecordNo() {
        return this.recordNo;
    }

    public void setRecordNo(String recordNo) {
        this.recordNo = recordNo;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public Date getDob() {
        return this.dob;
    }

    public void setDob(Date dob) {
        this.dob = dob;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    //This method writes the values of contact object with System.out.println(Emp.toString()) code
    @Override
    public String toString() {
        return "user"
                + "\n\t RecordNo: " + this.recordNo
                + "\n\t EmployeeName: " + this.name
                + "\n\t Age: " + this.age
                + "\n\t Sex: " + this.sex
                + "\n\t Date of Birth: " + this.dob
                + "\n\t Remark: " + this.remark;
    }

}
